export const PAISES = [
  { nomePais: 'United Arab Emirates', codigoMoeda: 'AED', codigoBandeira: 'AE' },
  { nomePais: 'Afghanistan', codigoMoeda: 'AFN', codigoBandeira: 'AF' },
  { nomePais: 'Albania', codigoMoeda: 'ALL', codigoBandeira: 'AL' },
  { nomePais: 'Armenia', codigoMoeda: 'AMD', codigoBandeira: 'AM' },
  { nomePais: 'Netherlands Antilles', codigoMoeda: 'ANG', codigoBandeira: 'AN' },
  { nomePais: 'Angola', codigoMoeda: 'AOA', codigoBandeira: 'AO' },
  { nomePais: 'Argentina', codigoMoeda: 'ARS', codigoBandeira: 'AR' },
  { nomePais: 'Australia', codigoMoeda: 'AUD', codigoBandeira: 'AU' },
  { nomePais: 'Aruba', codigoMoeda: 'AWG', codigoBandeira: 'AW' },
  { nomePais: 'Azerbaijan', codigoMoeda: 'AZN', codigoBandeira: 'AZ' },
  { nomePais: 'Bosnia and Herzegovina', codigoMoeda: 'BAM', codigoBandeira: 'BA' },
  { nomePais: 'Barbados', codigoMoeda: 'BBD', codigoBandeira: 'BB' },
  { nomePais: 'Bangladesh', codigoMoeda: 'BDT', codigoBandeira: 'BD' },
  { nomePais: 'Bulgaria', codigoMoeda: 'BGN', codigoBandeira: 'BG' },
  { nomePais: 'Bahrain', codigoMoeda: 'BHD', codigoBandeira: 'BH' },
  { nomePais: 'Burundi', codigoMoeda: 'BIF', codigoBandeira: 'BI' },
  { nomePais: 'Bermuda', codigoMoeda: 'BMD', codigoBandeira: 'BM' },
  { nomePais: 'Brunei', codigoMoeda: 'BND', codigoBandeira: 'BN' },
  { nomePais: 'Bolivia', codigoMoeda: 'BOB', codigoBandeira: 'BO' },
  { nomePais: 'Brazil', codigoMoeda: 'BRL', codigoBandeira: 'BR' },
  { nomePais: 'Bahamas', codigoMoeda: 'BSD', codigoBandeira: 'BS' },
  { nomePais: 'Bhutan', codigoMoeda: 'BTN', codigoBandeira: 'BT' },
  { nomePais: 'Botswana', codigoMoeda: 'BWP', codigoBandeira: 'BW' },
  { nomePais: 'Belarus', codigoMoeda: 'BYN', codigoBandeira: 'BY' },
  { nomePais: 'Belize', codigoMoeda: 'BZD', codigoBandeira: 'BZ' },
  { nomePais: 'Canada', codigoMoeda: 'CAD', codigoBandeira: 'CA' },
  { nomePais: 'Democratic Republic of the Congo', codigoMoeda: 'CDF', codigoBandeira: 'CD' },
  { nomePais: 'Congo', codigoMoeda: 'XAF', codigoBandeira: 'CG' },
  { nomePais: 'Switzerland', codigoMoeda: 'CHF', codigoBandeira: 'CH' },
  { nomePais: 'Chile', codigoMoeda: 'CLP', codigoBandeira: 'CL' },
  { nomePais: 'China', codigoMoeda: 'CNY', codigoBandeira: 'CN' },
  { nomePais: 'Colombia', codigoMoeda: 'COP', codigoBandeira: 'CO' },
  { nomePais: 'Costa Rica', codigoMoeda: 'CRC', codigoBandeira: 'CR' },
  { nomePais: 'Cuba', codigoMoeda: 'CUP', codigoBandeira: 'CU' },
  { nomePais: 'Cape Verde', codigoMoeda: 'CVE', codigoBandeira: 'CV' },
  { nomePais: 'Czech Republic', codigoMoeda: 'CZK', codigoBandeira: 'CZ' },
  { nomePais: 'Germany', codigoMoeda: 'EUR', codigoBandeira: 'DE' },
  { nomePais: 'Djibouti', codigoMoeda: 'DJF', codigoBandeira: 'DJ' },
  { nomePais: 'Denmark', codigoMoeda: 'DKK', codigoBandeira: 'DK' },
  { nomePais: 'Dominican Republic', codigoMoeda: 'DOP', codigoBandeira: 'DO' },
  { nomePais: 'Algeria', codigoMoeda: 'DZD', codigoBandeira: 'DZ' },
  { nomePais: 'Egypt', codigoMoeda: 'EGP', codigoBandeira: 'EG' },
  { nomePais: 'Eritrea', codigoMoeda: 'ERN', codigoBandeira: 'ER' },
  { nomePais: 'Spain', codigoMoeda: 'EUR', codigoBandeira: 'ES' },
  { nomePais: 'Estonia', codigoMoeda: 'EUR', codigoBandeira: 'EE' },
  { nomePais: 'Ethiopia', codigoMoeda: 'ETB', codigoBandeira: 'ET' },
  { nomePais: 'Finland', codigoMoeda: 'EUR', codigoBandeira: 'FI' },
  { nomePais: 'Fiji', codigoMoeda: 'FJD', codigoBandeira: 'FJ' },
  { nomePais: 'Falkland Islands', codigoMoeda: 'FKP', codigoBandeira: 'FK' },
  { nomePais: 'Faroe Islands', codigoMoeda: 'FOK', codigoBandeira: 'FO' },
  { nomePais: 'France', codigoMoeda: 'EUR', codigoBandeira: 'FR' },
  { nomePais: 'Gabon', codigoMoeda: 'XOF', codigoBandeira: 'GA' },
  { nomePais: 'United Kingdom', codigoMoeda: 'GBP', codigoBandeira: 'GB' },
  { nomePais: 'Grenada', codigoMoeda: 'XCD', codigoBandeira: 'GD' },
  { nomePais: 'Georgia', codigoMoeda: 'GEL', codigoBandeira: 'GE' },
  { nomePais: 'French Guiana', codigoMoeda: 'EUR', codigoBandeira: 'GF' },
  { nomePais: 'Ghana', codigoMoeda: 'GHS', codigoBandeira: 'GH' },
  { nomePais: 'Gibraltar', codigoMoeda: 'GIP', codigoBandeira: 'GI' },
  { nomePais: 'Greenland', codigoMoeda: 'DKK', codigoBandeira: 'GL' },
  { nomePais: 'The Gambia', codigoMoeda: 'GMD', codigoBandeira: 'GM' },
  { nomePais: 'Guinea', codigoMoeda: 'GNF', codigoBandeira: 'GN' },
  { nomePais: 'Equatorial Guinea', codigoMoeda: 'XAF', codigoBandeira: 'GQ' },
  { nomePais: 'Greece', codigoMoeda: 'EUR', codigoBandeira: 'GR' },
  { nomePais: 'South Georgia and the South Sandwich Islands', codigoMoeda: 'GBP', codigoBandeira: 'GS' },
  { nomePais: 'Guatemala', codigoMoeda: 'GTQ', codigoBandeira: 'GT' },
  { nomePais: 'Guam', codigoMoeda: 'USD', codigoBandeira: 'GU' },
  { nomePais: 'Guinea-Bissau', codigoMoeda: 'XOF', codigoBandeira: 'GW' },
  { nomePais: 'Guyana', codigoMoeda: 'GYD', codigoBandeira: 'GY' },
  { nomePais: 'Hong Kong', codigoMoeda: 'HKD', codigoBandeira: 'HK' },
  { nomePais: 'Honduras', codigoMoeda: 'HNL', codigoBandeira: 'HN' },
  { nomePais: 'Croatia', codigoMoeda: 'HRK', codigoBandeira: 'HR' },
  { nomePais: 'Haiti', codigoMoeda: 'HTG', codigoBandeira: 'HT' },
  { nomePais: 'Hungary', codigoMoeda: 'HUF', codigoBandeira: 'HU' },
  { nomePais: 'Indonesia', codigoMoeda: 'IDR', codigoBandeira: 'ID' },
  { nomePais: 'Ireland', codigoMoeda: 'EUR', codigoBandeira: 'IE' },
  { nomePais: 'Israel', codigoMoeda: 'ILS', codigoBandeira: 'IL' },
  { nomePais: 'Isle of Man', codigoMoeda: 'IMP', codigoBandeira: 'IM' },
  { nomePais: 'India', codigoMoeda: 'INR', codigoBandeira: 'IN' },
  { nomePais: 'Iraq', codigoMoeda: 'IQD', codigoBandeira: 'IQ' },
  { nomePais: 'Iran', codigoMoeda: 'IRR', codigoBandeira: 'IR' },
  { nomePais: 'Iceland', codigoMoeda: 'ISK', codigoBandeira: 'IS' },
  { nomePais: 'Italy', codigoMoeda: 'EUR', codigoBandeira: 'IT' },
  { nomePais: 'Jersey', codigoMoeda: 'JEP', codigoBandeira: 'JE' },
  { nomePais: 'Jamaica', codigoMoeda: 'JMD', codigoBandeira: 'JM' },
  { nomePais: 'Jordan', codigoMoeda: 'JOD', codigoBandeira: 'JO' },
  { nomePais: 'Japan', codigoMoeda: 'JPY', codigoBandeira: 'JP' },
  { nomePais: 'Kenya', codigoMoeda: 'KES', codigoBandeira: 'KE' },
  { nomePais: 'Kyrgyzstan', codigoMoeda: 'KGS', codigoBandeira: 'KG' },
  { nomePais: 'Cambodia', codigoMoeda: 'KHR', codigoBandeira: 'KH' },
  { nomePais: 'Kiribati', codigoMoeda: 'KID', codigoBandeira: 'KI' },
  { nomePais: 'Comoros', codigoMoeda: 'KMF', codigoBandeira: 'KM' },
  { nomePais: 'South Korea', codigoMoeda: 'KRW', codigoBandeira: 'KR' },
  { nomePais: 'Kuwait', codigoMoeda: 'KWD', codigoBandeira: 'KW' },
  { nomePais: 'Cayman Islands', codigoMoeda: 'KYD', codigoBandeira: 'KY' },
  { nomePais: 'Kazakhstan', codigoMoeda: 'KZT', codigoBandeira: 'KZ' },
  { nomePais: 'Laos', codigoMoeda: 'LAK', codigoBandeira: 'LA' },
  { nomePais: 'Lebanon', codigoMoeda: 'LBP', codigoBandeira: 'LB' },
  { nomePais: 'Sri Lanka', codigoMoeda: 'LKR', codigoBandeira: 'LK' },
  { nomePais: 'Liberia', codigoMoeda: 'LRD', codigoBandeira: 'LR' },
  { nomePais: 'Lesotho', codigoMoeda: 'LSL', codigoBandeira: 'LS' },
  { nomePais: 'Lithuania', codigoMoeda: 'EUR', codigoBandeira: 'LT' },
  { nomePais: 'Luxembourg', codigoMoeda: 'EUR', codigoBandeira: 'LU' },
  { nomePais: 'Latvia', codigoMoeda: 'EUR', codigoBandeira: 'LV' },
  { nomePais: 'Libya', codigoMoeda: 'LYD', codigoBandeira: 'LY' },
  { nomePais: 'Morocco', codigoMoeda: 'MAD', codigoBandeira: 'MA' },
  { nomePais: 'Monaco', codigoMoeda: 'EUR', codigoBandeira: 'MC' },
  { nomePais: 'Moldova', codigoMoeda: 'MDL', codigoBandeira: 'MD' },
  { nomePais: 'Montenegro', codigoMoeda: 'EUR', codigoBandeira: 'ME' },
  { nomePais: 'Madagascar', codigoMoeda: 'MGA', codigoBandeira: 'MG' },
  { nomePais: 'Marshall Islands', codigoMoeda: 'USD', codigoBandeira: 'MH' },
  { nomePais: 'North Macedonia', codigoMoeda: 'MKD', codigoBandeira: 'MK' },
  { nomePais: 'Mali', codigoMoeda: 'XOF', codigoBandeira: 'ML' },
  { nomePais: 'Myanmar', codigoMoeda: 'MMK', codigoBandeira: 'MM' },
  { nomePais: 'Mongolia', codigoMoeda: 'MNT', codigoBandeira: 'MN' },
  { nomePais: 'Macau', codigoMoeda: 'MOP', codigoBandeira: 'MO' },
  { nomePais: 'Mauritania', codigoMoeda: 'MRU', codigoBandeira: 'MR' },
  { nomePais: 'Malta', codigoMoeda: 'EUR', codigoBandeira: 'MT' },
  { nomePais: 'Mauritius', codigoMoeda: 'MUR', codigoBandeira: 'MU' },
  { nomePais: 'Maldives', codigoMoeda: 'MVR', codigoBandeira: 'MV' },
  { nomePais: 'Malawi', codigoMoeda: 'MWK', codigoBandeira: 'MW' },
  { nomePais: 'Mexico', codigoMoeda: 'MXN', codigoBandeira: 'MX' },
  { nomePais: 'Malaysia', codigoMoeda: 'MYR', codigoBandeira: 'MY' },
  { nomePais: 'Mozambique', codigoMoeda: 'MZN', codigoBandeira: 'MZ' },
  { nomePais: 'Namibia', codigoMoeda: 'NAD', codigoBandeira: 'NA' },
  { nomePais: 'New Caledonia', codigoMoeda: 'XPF', codigoBandeira: 'NC' },
  { nomePais: 'Niger', codigoMoeda: 'XOF', codigoBandeira: 'NE' },
  { nomePais: 'Norfolk Island', codigoMoeda: 'AUD', codigoBandeira: 'NF' },
  { nomePais: 'Nigeria', codigoMoeda: 'NGN', codigoBandeira: 'NG' },
  { nomePais: 'Nicaragua', codigoMoeda: 'NIO', codigoBandeira: 'NI' },
  { nomePais: 'Netherlands', codigoMoeda: 'EUR', codigoBandeira: 'NL' },
  { nomePais: 'Norway', codigoMoeda: 'NOK', codigoBandeira: 'NO' },
  { nomePais: 'Nepal', codigoMoeda: 'NPR', codigoBandeira: 'NP' },
  { nomePais: 'Nauru', codigoMoeda: 'AUD', codigoBandeira: 'NR' },
  { nomePais: 'Niue', codigoMoeda: 'NZD', codigoBandeira: 'NU' },
  { nomePais: 'New Zealand', codigoMoeda: 'NZD', codigoBandeira: 'NZ' },
  { nomePais: 'Oman', codigoMoeda: 'OMR', codigoBandeira: 'OM' },
  { nomePais: 'Panama', codigoMoeda: 'PAB', codigoBandeira: 'PA' },
  { nomePais: 'Peru', codigoMoeda: 'PEN', codigoBandeira: 'PE' },
  { nomePais: 'Papua New Guinea', codigoMoeda: 'PGK', codigoBandeira: 'PG' },
  { nomePais: 'Philippines', codigoMoeda: 'PHP', codigoBandeira: 'PH' },
  { nomePais: 'Pakistan', codigoMoeda: 'PKR', codigoBandeira: 'PK' },
  { nomePais: 'Poland', codigoMoeda: 'PLN', codigoBandeira: 'PL' },
  { nomePais: 'Saint Pierre and Miquelon', codigoMoeda: 'EUR', codigoBandeira: 'PM' },
  { nomePais: 'Pitcairn Islands', codigoMoeda: 'NZD', codigoBandeira: 'PN' },
  { nomePais: 'Puerto Rico', codigoMoeda: 'USD', codigoBandeira: 'PR' },
  { nomePais: 'Portugal', codigoMoeda: 'EUR', codigoBandeira: 'PT' },
  { nomePais: 'Palau', codigoMoeda: 'USD', codigoBandeira: 'PW' },
  { nomePais: 'Paraguay', codigoMoeda: 'PYG', codigoBandeira: 'PY' },
  { nomePais: 'Qatar', codigoMoeda: 'QAR', codigoBandeira: 'QA' },
  { nomePais: 'Réunion', codigoMoeda: 'EUR', codigoBandeira: 'RE' },
  { nomePais: 'Romania', codigoMoeda: 'RON', codigoBandeira: 'RO' },
  { nomePais: 'Serbia', codigoMoeda: 'RSD', codigoBandeira: 'RS' },
  { nomePais: 'Russia', codigoMoeda: 'RUB', codigoBandeira: 'RU' },
  { nomePais: 'Rwanda', codigoMoeda: 'RWF', codigoBandeira: 'RW' },
  { nomePais: 'Saudi Arabia', codigoMoeda: 'SAR', codigoBandeira: 'SA' },
  { nomePais: 'Solomon Islands', codigoMoeda: 'SBD', codigoBandeira: 'SB' },
  { nomePais: 'Seychelles', codigoMoeda: 'SCR', codigoBandeira: 'SC' },
  { nomePais: 'Sudan', codigoMoeda: 'SDG', codigoBandeira: 'SD' },
  { nomePais: 'Sweden', codigoMoeda: 'SEK', codigoBandeira: 'SE' },
  { nomePais: 'Singapore', codigoMoeda: 'SGD', codigoBandeira: 'SG' },
  { nomePais: 'Saint Helena', codigoMoeda: 'SHP', codigoBandeira: 'SH' },
  { nomePais: 'Slovenia', codigoMoeda: 'EUR', codigoBandeira: 'SI' },
  { nomePais: 'Svalbard and Jan Mayen', codigoMoeda: 'NOK', codigoBandeira: 'SJ' },
  { nomePais: 'Slovakia', codigoMoeda: 'EUR', codigoBandeira: 'SK' },
  { nomePais: 'Sierra Leone', codigoMoeda: 'SLE', codigoBandeira: 'SL' },
  { nomePais: 'San Marino', codigoMoeda: 'EUR', codigoBandeira: 'SM' },
  { nomePais: 'Senegal', codigoMoeda: 'XOF', codigoBandeira: 'SN' },
  { nomePais: 'Somalia', codigoMoeda: 'SOS', codigoBandeira: 'SO' },
  { nomePais: 'Suriname', codigoMoeda: 'SRD', codigoBandeira: 'SR' },
  { nomePais: 'South Sudan', codigoMoeda: 'SSP', codigoBandeira: 'SS' },
  { nomePais: 'Sao Tome and Principe', codigoMoeda: 'STN', codigoBandeira: 'ST' },
  { nomePais: 'El Salvador', codigoMoeda: 'SVC', codigoBandeira: 'SV' },
  { nomePais: 'Syria', codigoMoeda: 'SYP', codigoBandeira: 'SY' },
  { nomePais: 'Eswatini', codigoMoeda: 'SZL', codigoBandeira: 'SZ' },
  { nomePais: 'Turks and Caicos Islands', codigoMoeda: 'USD', codigoBandeira: 'TC' },
  { nomePais: 'Chad', codigoMoeda: 'XAF', codigoBandeira: 'TD' },
  { nomePais: 'French Southern Territories', codigoMoeda: 'EUR', codigoBandeira: 'TF' },
  { nomePais: 'Togo', codigoMoeda: 'XOF', codigoBandeira: 'TG' },
  { nomePais: 'Thailand', codigoMoeda: 'THB', codigoBandeira: 'TH' },
  { nomePais: 'Tajikistan', codigoMoeda: 'TJS', codigoBandeira: 'TJ' },
  { nomePais: 'Tokelau', codigoMoeda: 'NZD', codigoBandeira: 'TK' },
  { nomePais: 'East Timor', codigoMoeda: 'USD', codigoBandeira: 'TL' },
  { nomePais: 'Turkmenistan', codigoMoeda: 'TMT', codigoBandeira: 'TM' },
  { nomePais: 'Tunisia', codigoMoeda: 'TND', codigoBandeira: 'TN' },
  { nomePais: 'Tonga', codigoMoeda: 'TOP', codigoBandeira: 'TO' },
  { nomePais: 'Turkey', codigoMoeda: 'TRY', codigoBandeira: 'TR' },
  { nomePais: 'Trinidad and Tobago', codigoMoeda: 'TTD', codigoBandeira: 'TT' },
  { nomePais: 'Tuvalu', codigoMoeda: 'TVD', codigoBandeira: 'TV' },
  { nomePais: 'Taiwan', codigoMoeda: 'TWD', codigoBandeira: 'TW' },
  { nomePais: 'Tanzania', codigoMoeda: 'TZS', codigoBandeira: 'TZ' },
  { nomePais: 'Ukraine', codigoMoeda: 'UAH', codigoBandeira: 'UA' },
  { nomePais: 'Uganda', codigoMoeda: 'UGX', codigoBandeira: 'UG' },
  { nomePais: 'United States Minor Outlying Islands', codigoMoeda: 'USD', codigoBandeira: 'UM' },
  { nomePais: 'Uruguay', codigoMoeda: 'UYU', codigoBandeira: 'UY' },
  { nomePais: 'Uzbekistan', codigoMoeda: 'UZS', codigoBandeira: 'UZ' },
  { nomePais: 'Holy See', codigoMoeda: 'EUR', codigoBandeira: 'VA' },
  { nomePais: 'Saint Vincent and the Grenadines', codigoMoeda: 'XCD', codigoBandeira: 'VC' },
  { nomePais: 'Venezuela', codigoMoeda: 'VES', codigoBandeira: 'VE' },
  { nomePais: 'British Virgin Islands', codigoMoeda: 'USD', codigoBandeira: 'VG' },
  { nomePais: 'U.S. Virgin Islands', codigoMoeda: 'USD', codigoBandeira: 'VI' },
  { nomePais: 'Vietnam', codigoMoeda: 'VND', codigoBandeira: 'VN' },
  { nomePais: 'Vanuatu', codigoMoeda: 'VUV', codigoBandeira: 'VU' },
  { nomePais: 'Samoa', codigoMoeda: 'WST', codigoBandeira: 'WS' },
  { nomePais: 'CEMAC', codigoMoeda: 'XAF', codigoBandeira: 'XA' },
  { nomePais: 'Organisation of Eastern Caribbean States', codigoMoeda: 'XCD', codigoBandeira: 'XB' },
  { nomePais: 'International Monetary Fund', codigoMoeda: 'XDR', codigoBandeira: 'XC' },
  { nomePais: 'CFA', codigoMoeda: 'XOF', codigoBandeira: 'XD' },
  { nomePais: 'Collectivités d’Outre-Mer', codigoMoeda: 'XPF', codigoBandeira: 'XE' },
  { nomePais: 'Yemen', codigoMoeda: 'YER', codigoBandeira: 'YEM' },
  { nomePais: 'Mayotte', codigoMoeda: 'EUR', codigoBandeira: 'YT' },
  { nomePais: 'South Africa', codigoMoeda: 'ZAR', codigoBandeira: 'ZA' },
  { nomePais: 'Zambia', codigoMoeda: 'ZMW', codigoBandeira: 'ZM' },
  { nomePais: 'Zimbabwe', codigoMoeda: 'ZWL', codigoBandeira: 'ZW' }
];